# Generated by Django 5.1.5 on 2025-02-04 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_des', models.TextField()),
                ('prduct_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
