# Generated by Django 5.1.5 on 2025-02-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quanitiy',
            field=models.IntegerField(),
        ),
    ]
