# Generated by Django 5.1.5 on 2025-02-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_order_quanitiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
