# Generated by Django 5.1.5 on 2025-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_productdetail_category_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=models.ImageField(upload_to='upload/products'),
        ),
    ]
