# Generated by Django 5.1.5 on 2025-02-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_customer_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ProductDetail',
            new_name='productDetail',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
