# Generated by Django 5.1.5 on 2025-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_rename_productdetail_order_productdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='sale_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
