# Generated by Django 5.1.5 on 2025-02-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_productdetail_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='sale_price',
            new_name='deal_price',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='is_sale',
            new_name='is_deal',
        ),
    ]
