# Generated by Django 5.1.5 on 2025-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_rename_sale_price_productdetail_deal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='is_deal',
            field=models.BooleanField(default=True),
        ),
    ]
