# Generated by Django 5.1.5 on 2025-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_productdetail_is_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
    ]
