# Generated by Django 5.1.5 on 2025-02-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quanitiy',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
